"""
clean_data.py

Purpose:
--------
Clean the raw e-commerce datasets generated by generate_data.py.

Tasks Performed:
1. Load raw CSV files
2. Remove duplicates
3. Handle missing values
4. Fix data types
5. Remove invalid records
6. Validate referential integrity
7. Export cleaned CSV files
"""

import os
import pandas as pd

# ==========================================================
# Folder Paths
# ==========================================================

RAW_PATH = os.path.join("data", "raw")
CLEAN_PATH = os.path.join("data", "cleaned")

os.makedirs(CLEAN_PATH, exist_ok=True)

# ==========================================================
# Load CSV Files
# ==========================================================

print("\nLoading raw datasets...\n")

customers = pd.read_csv(os.path.join(RAW_PATH, "customers.csv"))
products = pd.read_csv(os.path.join(RAW_PATH, "products.csv"))
orders = pd.read_csv(os.path.join(RAW_PATH, "orders.csv"))
order_items = pd.read_csv(os.path.join(RAW_PATH, "order_items.csv"))

# ==========================================================
# Display Original Shape
# ==========================================================

print("=" * 60)
print("Original Dataset Sizes")
print("=" * 60)

print(f"Customers   : {customers.shape}")
print(f"Products    : {products.shape}")
print(f"Orders      : {orders.shape}")
print(f"Order Items : {order_items.shape}")

# ==========================================================
# Remove Duplicate Records
# ==========================================================

print("\nRemoving duplicate records...")

customers = customers.drop_duplicates()
products = products.drop_duplicates()
orders = orders.drop_duplicates()
order_items = order_items.drop_duplicates()

# ==========================================================
# Handle Missing Values
# ==========================================================

print("Handling missing values...")

customers["email"] = customers["email"].fillna("unknown@email.com")
customers["city"] = customers["city"].fillna("Unknown")

products["category"] = products["category"].fillna("Unknown")

# ==========================================================
# Convert Data Types
# ==========================================================

print("Converting data types...")

orders["order_date"] = pd.to_datetime(
    orders["order_date"],
    errors="coerce"
)

# ==========================================================
# Remove Invalid Dates
# ==========================================================

print("Removing future dates...")

today = pd.Timestamp.today()

orders = orders[
    orders["order_date"] <= today
]

# ==========================================================
# Remove Invalid Product Prices
# ==========================================================

print("Removing invalid prices...")

products = products[
    products["price"] > 0
]

# ==========================================================
# Remove Invalid Quantities
# ==========================================================

print("Removing invalid quantities...")

order_items = order_items[
    order_items["quantity"] > 0
]

# ==========================================================
# Referential Integrity Checks
# ==========================================================

print("Validating foreign keys...")

# -----------------------------
# Valid Customers
# -----------------------------

valid_customer_ids = customers["customer_id"]

orders = orders[
    orders["customer_id"].isin(valid_customer_ids)
]

# -----------------------------
# Valid Orders
# -----------------------------

valid_order_ids = orders["order_id"]

order_items = order_items[
    order_items["order_id"].isin(valid_order_ids)
]

# -----------------------------
# Valid Products
# -----------------------------

valid_product_ids = products["product_id"]

order_items = order_items[
    order_items["product_id"].isin(valid_product_ids)
]

# ==========================================================
# Check Missing Values
# ==========================================================

print("\nMissing Values After Cleaning\n")

print("Customers")
print(customers.isnull().sum())

print("\nProducts")
print(products.isnull().sum())

print("\nOrders")
print(orders.isnull().sum())

print("\nOrder Items")
print(order_items.isnull().sum())

# ==========================================================
# Save Cleaned Files
# ==========================================================

print("\nSaving cleaned datasets...\n")

customers.to_csv(
    os.path.join(CLEAN_PATH, "customers_clean.csv"),
    index=False
)

products.to_csv(
    os.path.join(CLEAN_PATH, "products_clean.csv"),
    index=False
)

orders.to_csv(
    os.path.join(CLEAN_PATH, "orders_clean.csv"),
    index=False
)

order_items.to_csv(
    os.path.join(CLEAN_PATH, "order_items_clean.csv"),
    index=False
)

# ==========================================================
# Final Summary
# ==========================================================

print("=" * 60)
print("Cleaning Summary")
print("=" * 60)

print(f"Customers   : {len(customers)}")
print(f"Products    : {len(products)}")
print(f"Orders      : {len(orders)}")
print(f"Order Items : {len(order_items)}")

print("\nCleaned datasets saved successfully!")

print(f"\nLocation: {CLEAN_PATH}")